#!/usr/bin/env python3
from pathlib import Path
R=Path('.')
def p(f,a,b):
 x=(R/f).read_text(encoding='utf-8-sig')
 if a not in x: raise SystemExit(f'{f}: fragment not found')
 (R/f).write_text(x.replace(a,b),encoding='utf-8')

p('deploy/yandex/Caddyfile','# Порт 8001 проброшен как 0.0.0.0:8001:8001 в docker-compose (Caddy идёт\n    # через хостовой loopback; UFW закрывает 8001 извне, monitoring-стек\n    # ходит через Docker-сеть msp_default по имени `backend`). См. CHANGELOG v5.1.','# Актуальный Compose публикует порт только как `127.0.0.1:8001:8001`.\n    # Caddy идёт через loopback, monitoring — по Docker DNS `backend`.\n    # Публичный интерфейс не должен слушать 8001.')
p('backend/.env.example','# (не self-signed). Локально вебхук не работает — для разработки\n# используется long-polling (см. docs/MAX_SETUP.md).','# (не self-signed). Встроенного long-polling режима нет: локально нужен mock\n# или временный HTTPS-туннель. Alertmanager использует отдельный pymax userbot.')
p('backend/.env.example','для msp-claude.online (TXT + DKIM на Namecheap Advanced DNS).','для msp-claude.online: ownership — по подсказке консоли, DKIM — только\n#      CNAME `<selector>._domainkey → <selector>.dkim.pstbx.ru`.')
p('deploy/yandex/STALWART_RELAY_MODE.md','> ⚠️ **УСТАРЕЛО (deprecated since v4.3).** Этот документ описывает Stalwart\n> Mail в submit-only режиме как relay через smarthost. **В проде Stalwart\n> больше не используется** — outbound mail идёт напрямую через **Yandex\n> Cloud Postbox (MSA :465, implicit TLS)**, см. CHANGELOG v4.3 и v5.4.\n> Файл сохранён для истории и на случай отката. Актуальный мейл-стек:\n> [`deploy/yandex/README.md`](README.md) → раздел "Postbox".','> **Статус: условный production-компонент.** Backend, Alertmanager, Grafana и\n> Vaultwarden отправляют напрямую через Postbox `:465` implicit TLS. Stalwart\n> запускается только профилем `mail`, если нужны локальные ящики/IMAP. После\n> restore его route credentials остаются в RocksDB: `.env` их не обновляет.')
p('deploy/yandex/STALWART_RELAY_MODE.md','DKIM-ключ генерируется в Stalwart admin UI:\n`Settings → Domains → <domain> → Generate DKIM key`.\nСкопируйте TXT и положите в DNS у регистратора.\n\n> **Актуализация 28.09.2026**: в production подпись DKIM делает **Postbox** — публикуются CNAME-записи из консоли Postbox (`<selector>._domainkey → <selector>.dkim.pstbx.ru`). Собственный DKIM-ключ Stalwart не используется.','В production DKIM подписывает **Postbox**. Публикуйте CNAME из его консоли:\n`<selector>._domainkey → <selector>.dkim.pstbx.ru`. Собственный DKIM TXT\nStalwart для этого контура не создаётся.')
p('technical/0_Common/SERVICES/mail_dns.md','# DKIM (ожидаем selector \'default\' или \'mail\')\nfor SEL in default mail selector1 s1; do\n  DKIM=$(dig +short TXT ${SEL}._domainkey.$DOMAIN | grep -c "v=DKIM1")\n  echo "dns_dkim_present{selector=\\"$SEL\\"} $DKIM" >> $TMP\ndone','# DKIM: TXT для обычных MTA или CNAME для Postbox. Селекторы Postbox\n# передаются из консоли, а не угадываются.\nfor SEL in default mail selector1 s1 "${POSTBOX_DKIM_SELECTOR_1:-}" "${POSTBOX_DKIM_SELECTOR_2:-}"; do\n  [[ -z "$SEL" ]] && continue\n  TXT_N=$(dig +short TXT "${SEL}._domainkey.${DOMAIN}" | grep -ci "v=DKIM1" || true)\n  CNAME_N=$(dig +short CNAME "${SEL}._domainkey.${DOMAIN}" | grep -ci "\\.dkim\\.pstbx\\.ru\\.?$" || true)\n  (( TXT_N > 0 || CNAME_N > 0 )) && DKIM=1 || DKIM=0\n  echo "dns_dkim_present{selector=\\"$SEL\\"} $DKIM" >> "$TMP"\ndone')
p('docs/deployment/secrets_management.md','Все сервисы работают на одной Yandex Cloud VM (static IP: `130.193.49.21`). Доступ — только через AmneziaWG туннель (`10.9.0.1`, UDP/443). SSH: `ssh -i ~/.ssh/id_ed25519_yc_new ubuntu@10.9.0.1`.','Пилот использует одну Yandex Cloud VM со статическим IP. IP и cloud ID берутся из runtime inventory, а не из документации. После проверки AWG публичный TCP/22 закрывается и в Security Group, и в UFW.')
p('docs/deployment/secrets_management.md','Docker volume msp-max-alerter-data     # pymax session (SMS auth)','`monitoring/max-session/max.db`        # bind-mounted pymax session; credential')
p('docs/deployment/secrets_management.md','| MAX session | При истечении | `python3 auth.py --phone +79990703823 --session /opt/msp/Newbie/deploy/yandex/monitoring/max-session/max.db` |','| MAX session | При истечении | `sudo docker exec -it msp-max-alerter python -m max_alerter.auth --authorize` |')
p('docs/deployment/secrets_management.md','| `msp-claude.online` | A | `130.193.49.21` |','| `msp-claude.online` | A | `<CURRENT_PUBLIC_IP>` из inventory |')
p('book/chapters/21-alerting-и-доставка-в-max.md','sudo docker exec msp-max-alerter python -m max_alerter.auth\ncurl -fsS','sudo docker exec msp-max-alerter python -m max_alerter.auth  # check, SMS не отправляет\nsudo docker exec -it msp-max-alerter python -m max_alerter.auth --authorize  # только ручная авторизация\ncurl -fsS')
x=(R/'book/build_full_book.py').read_text(encoding='utf-8')
x=x.replace('sudo docker exec msp-max-alerter python -m max_alerter.auth\\n','sudo docker exec msp-max-alerter python -m max_alerter.auth  # check\\nsudo docker exec -it msp-max-alerter python -m max_alerter.auth --authorize  # manual auth\\n')
(R/'book/build_full_book.py').write_text(x,encoding='utf-8')
p('technical/1_Bronze/EXECUTOR/SOP_executor_bronze.md','# SOP — Bronze · Сторона ИСПОЛНИТЕЛЯ','# SOP — Bronze · Сторона ИСПОЛНИТЕЛЯ\n\n> **Legacy/учебный SOP.** Для текущего production каноничны `docs/deployment/DEPLOY_RUNBOOK.md` и `deploy/yandex/README.md`. Backend доступен только через loopback, alerts идут в MAX + email, а public SSH закрывается после проверки AWG.')
p('technical/1_Bronze/EXECUTOR/SOP_executor_bronze.md','sudo ufw allow 22/tcp     comment "SSH"','sudo ufw allow 22/tcp     comment "TEMP bootstrap SSH; закрыть после проверки AWG"')
for f in ['infra/terraform/cloud-init/landing.yaml','infra/terraform/cloud-init/bastion.yaml']:
 p(f,'  - ufw allow 22/tcp\n',"  # TEMP bootstrap: SG обязана ограничивать ADMIN_CIDR; после AWG закрыть public 22.\n  - ufw allow 22/tcp comment 'TEMP bootstrap SSH'\n")
(R/'docs/runbooks/R-smtp-down.md').write_text('''# R-smtp-down · Почта недоступна\n\n**Основной production path:** сервис → `postbox.cloud.yandex.net:465` implicit TLS. Stalwart — optional profile `mail`.\n\n## Диагностика\n\n1. Определить отправителя: backend, Alertmanager, Grafana, Vaultwarden или Stalwart.\n2. `535 Authentication failed`: username должен быть ID API-ключа, не service-account ID.\n3. `550 identity not verified`: проверить identity и DKIM CNAME из Postbox.\n4. Для Stalwart проверить очередь `x:QueuedMessage/get` и отсутствие `bootstrap mode`.\n\n## Восстановление\n\n- После изменения `.env`: `docker compose up -d --force-recreate <service>`; `restart` env не перечитывает.\n- Восстановленный `postbox-outbound` обновить через `x:MtaRoute/set`, затем перезапустить Stalwart.\n- При bootstrap mode восстановить оба тома: `stalwart-etc` и `stalwart-data`.\n- После фикса отправить контрольное письмо и сохранить message-id/ошибку без секретов.\n''',encoding='utf-8')
validator='''#!/usr/bin/env python3\nfrom pathlib import Path\nimport sys\nR=Path(__file__).resolve().parents[1]; e=[]\ndef t(f): return (R/f).read_text(encoding="utf-8-sig")\ndef n(f,s):\n if s not in t(f): e.append(f"{f}: missing {s}")\ndef b(f,s):\n if s in t(f): e.append(f"{f}: stale {s}")\nn("deploy/yandex/docker-compose.yml","127.0.0.1:8001:8001"); b("deploy/yandex/Caddyfile","0.0.0.0:8001:8001")\nn("services/max_alerter/requirements.txt","maxapi-python==2.4.1"); n("docs/MAX_SETUP.md","auth --authorize")\nn("book/chapters/21-alerting-и-доставка-в-max.md","auth --authorize"); b("backend/.env.example","используется long-polling")\nn("technical/0_Common/SERVICES/mail_dns.md","CNAME_N="); b("deploy/yandex/STALWART_RELAY_MODE.md","Скопируйте TXT и положите в DNS")\nb("docs/deployment/secrets_management.md","python3 auth.py --phone")\nfor f in ["infra/terraform/cloud-init/landing.yaml","infra/terraform/cloud-init/bastion.yaml"]: n(f,"TEMP bootstrap SSH")\nif e:\n print("DEPLOYMENT FRESHNESS FAILED",*e,sep="\\n - "); sys.exit(1)\nprint("DEPLOYMENT FRESHNESS OK")\n'''
(R/'scripts/validate_deployment_freshness.py').write_text(validator,encoding='utf-8')
p('.github/workflows/quality.yml','  operational-shell-syntax:\n','  deployment-freshness:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: python scripts/validate_deployment_freshness.py\n  operational-shell-syntax:\n')
report='''# Ревизия deployment-информации — 29.09.2026\n\nСравнены миграционные и deploy-коммиты `ead78a4`, `c6d3c3f`, `a6483be`, `2ba6541`, `cffbbf9`, `6e40c8d`, `1fb81d8`, `2e06f9c`, `89249e4` и текущее состояние `58209a9`.\n\nЗакреплено: loopback для backend; MAX userbot с явным `--authorize`; Postbox `:465`, API-key ID и DKIM CNAME; оба Stalwart volume и запрет bootstrap mode; внешний TCP/TLS gate до DNS; закрытие public SSH после AWG; clean-room restore как доказательство backup.\n\nИсправлены Caddy, env-примеры, mail/DKIM, Stalwart, secrets, SMTP runbook, книга, Bronze SOP и Terraform cloud-init. Добавлен CI validator против возврата старых предположений.\n\nLive-инфраструктура всё ещё требует внешнего скана, тестового MAX/email, clean-room restore с RTO/RPO и проверки SG/UFW: репозиторий не может доказать эти факты сам.\n'''
(R/'docs/audit/repository_deployment_freshness_2026-09.md').write_text(report,encoding='utf-8')
p('docs/NAVIGATION.md','- [Уроки deployment](deployment/DEPLOYMENT_LESSONS.md)','- [Уроки deployment](deployment/DEPLOYMENT_LESSONS.md)\n- [Ревизия свежести всего репозитория](audit/repository_deployment_freshness_2026-09.md)')
print('PATCHED')
