groups:
  - name: ssl
    rules:
      - alert: SSLExpiringSoon
        expr: (probe_ssl_earliest_cert_expiry - time()) / 86400 < 14
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "SSL cert expiring in <14d for {{ $labels.instance }}"

      - alert: SSLExpired
        expr: (probe_ssl_earliest_cert_expiry - time()) < 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "SSL cert EXPIRED for {{ $labels.instance }}"
