---
alertmanager_install_mode: apt
alertmanager_tg_bot_token: ""
alertmanager_smtp_password: ""
alertmanager_tg_chat_id_general: ""
alertmanager_tg_chat_id_p1: ""
alertmanager_tg_chat_id_backup: ""
alertmanager_smtp_from: "alert@msp-claude.online"
alertmanager_smtp_smarthost: "smtp.yandex.ru:587"
alertmanager_smtp_user: "alert@msp-claude.online"
alertmanager_email_p3_to: "alert@msp-claude.online"
alertmanager_resolve_timeout: "5m"
