from pathlib import Path
import re, json
R=Path('/data/MSPShield_Academy_MD'); C=R/'chapters'; C.mkdir(exist_ok=True)
commit='89249e43a4e8b2e90d562307ef244ba95288c64c'
repo=f'https://github.com/i1yxaluk-del/Newbie/blob/{commit}/'
# number,title,scenario,concepts,example,steps,failures,repo_paths
D=[
(1,'От услуги к работающей системе','Клиент видит сайт и обещание поддержки, но Owner должен видеть цепочку людей, процессов, кода и данных.',['Система — это компоненты и связи, дающие наблюдаемый результат. Компонент без владельца и способа проверки превращается в скрытый риск.','Состояние — информация, переживающая отдельный запрос: Mongo-документ, volume, MAX-session, договорный scope. Процесс сам по себе не равен состоянию.','Source of truth выбирается по типу факта: Git для кода, Kaiten для работы, Vaultwarden для секретов, договор для обязательств, Prometheus для telemetry.'],'''```mermaid\nflowchart LR\nU[Пользователь] -->|HTTPS| C[Caddy]\nC -->|HTTP :8001| B[FastAPI]\nB --> M[(MongoDB)]\nB --> K[Kaiten/outbox]\nP[Prometheus] --> A[Alertmanager]\nA --> X[MAX alerter]\n```''',['Перерисуйте схему без подсказки.','Для каждой стрелки подпишите протокол и ошибку, которая может на ней возникнуть.','Укажите, где хранится состояние и кто его восстанавливает.'],['Сайт 200, форма не создаёт заявку — проверять frontend→API и outbox.','Dashboard зелёный, клиент недоступен — telemetry покрывает не весь пользовательский путь.'],['README.md','docs/NAVIGATION.md']),
(2,'Исследование незнакомой системы без угадывания','После инцидента документация и фактическая конфигурация расходятся. Нужно установить правду, ничего не ломая.',['Начинайте с наблюдения: версия, process, socket, config path, log и health. Гипотеза появляется после факта, а не вместо него.','README описывает намерение; исполняемый Compose, systemd unit и runtime inspect показывают реализацию. Источник может устареть, поэтому важна привязка к commit.','Незнание фиксируется явно. Надпись ASSUMPTION безопаснее уверенного вымысла, потому что её можно проверить.'],'''```bash\ngit rev-parse HEAD\ndocker compose config --services\ndocker compose ps\nss -lntp\ncurl -fsS http://127.0.0.1:8001/api/health\n```''',['Соберите read-only inventory одного сервиса.','Сравните README, Compose и runtime.','Запишите три подтверждённых факта и одно расхождение.'],['`docker ps` пуст — возможно выбран другой context или нет прав к socket.','Health 200 не доказывает доступность зависимостей, если endpoint их не проверяет.'],['docs/NAVIGATION.md','docs/training/JUNIOR_OPERATIONS_GUIDE.md']),
(3,'Файлы, каталоги, пользователи и права','Restore-скрипт не видит архивы, хотя root видит их через `ls`.',['Путь разрешается от root `/` либо текущего каталога. Каталог требует `x` для прохода; чтение файла не помогает, если нет прохода по родителю.','Mode `640` означает rw для владельца, r для группы и ничего для остальных. Для `.env` обычно нужен `600`, чтобы только владелец читал и менял файл.','Shell раскрывает `*` до запуска `sudo`. Если текущий пользователь не может прочитать каталог, root-команда получит буквальный шаблон или пустой список.'],'''```bash\nnamei -l /opt/msp-backups/current/volumes/data.tar.gz\nstat -c '%U:%G %a %n' /opt/msp-backups/current/volumes/*\nsudo sh -c 'cp /root/restore/*.tar.gz /tmp/migration/'\n```''',['Создайте root-only каталог и архив.','Воспроизведите ошибку `sudo cp /root/x/*.tar.gz /tmp/`.','Объясните, почему `sudo sh -c` меняет результат.'],['Permission denied — исследовать каждый компонент пути через `namei -l`.','Файл есть, glob не раскрылся — expansion выполнил пользовательский shell.'],['docs/deployment/MIGRATION_RUNBOOK.md','migration/restore-on-vm.sh']),
(4,'Процессы, signals, systemd и журналы','Caddy установлен, но после reboot сайт не поднялся.',['Процесс — выполняющийся экземпляр программы с PID, окружением и открытыми descriptors. Exit code относится к завершившемуся процессу.','Signal просит процесс выполнить действие; SIGTERM даёт шанс завершиться корректно, SIGKILL — нет.','systemd хранит желаемое состояние unit и зависимости. `restart` запускает старое определение; после изменения unit нужен `daemon-reload`.'],'''```bash\nsystemctl status caddy --no-pager\nsystemctl cat caddy\njournalctl -u caddy -b --no-pager -n 100\nsystemctl show caddy -p Environment -p ExecStart\n```''',['Создайте учебный unit для `python -m http.server`.','Сломайте путь ExecStart и найдите код завершения.','Исправьте unit, выполните daemon-reload и enable.'],['Unit active, сайт недоступен — проверить socket и firewall.','Переменная есть в shell, но нет в service — systemd не наследует интерактивное окружение.'],['deploy/yandex/setup-on-vm.sh','docs/deployment/DEPLOY_RUNBOOK.md']),
(5,'Shell без магии','Однострочная команда сработала вручную, но повредила скрипт автоматизации.',['Shell сначала разбивает строку, выполняет expansion и redirection, затем запускает программу. Поэтому кавычки — часть логики, а не оформление.','`set -Eeuo pipefail` останавливает многие тихие ошибки: ненулевой exit, unset variable и ошибку внутри pipeline. Но ожидаемые ненулевые результаты нужно обрабатывать явно.','Секрет в аргументе виден в history и иногда process list. Передавайте его через защищённый файл, stdin или secret mechanism конкретного инструмента.'],'''```bash\nset -Eeuo pipefail\nROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"\n[[ -f "$ROOT/backend/.env" ]] || { echo "нет env" >&2; exit 1; }\n```''',['Разберите строку вычисления ROOT по операциям.','Добавьте trap, который сообщает номер упавшей строки.','Проверьте скрипт с пробелом в имени каталога.'],['Pipeline зелёный при ошибке первой команды — нет `pipefail`.','Пустая переменная стала путём `/` — нет `-u` и проверки значения.'],['scripts/deployment/preflight.sh']),
(6,'IP, маршрут, TCP, порт и DNS','IP пингуется, но из РФ не открываются 22/80/443.',['IP отвечает на вопрос, к какому интерфейсу доставлять packet; route выбирает следующий hop. ICMP echo и TCP SYN — разные протоколы и могут фильтроваться по-разному.','Listening socket связывает process с address:port. `127.0.0.1:8001` доступен только локально; `0.0.0.0:8001` принимает на всех интерфейсах.','DNS возвращает записи, но не проверяет TCP, TLS или application. TTL влияет на время распространения изменения и rollback.'],'''```bash\ndig +short example.org A\nip route get 1.1.1.1\nss -lntp\nnc -vz -w3 203.0.113.10 443\ncurl -v --connect-timeout 5 https://example.org/health\n```''',['Сделайте проверки с VM и из внешней сети.','Сопоставьте timeout, refused и HTTP 503.','Постройте дерево диагностики снизу вверх.'],['Timeout — packet/route/firewall, а не доказательство падения app.','Refused — host достижим, но socket не слушает либо reject активен.'],['docs/deployment/DEPLOY_RUNBOOK.md','docs/deployment/MIGRATION_RUNBOOK.md']),
(7,'HTTP, TLS и reverse proxy','Caddy отдаёт 503 после чистой установки.',['HTTP request содержит method, target, headers и body; response — status, headers и body. 503 означает, что HTTP-ответ уже получен.','TLS проверяет владение private key и цепочку доверия. SNI позволяет выбрать сертификат по hostname до HTTP.','Reverse proxy принимает внешний TLS и создаёт отдельное соединение к upstream. Ошибка proxy и ошибка backend находятся на разных участках.'],'''```caddy\n{$MSP_DOMAIN} {\n  handle /api/* { reverse_proxy 127.0.0.1:8001 }\n  root * /var/www/landing\n  file_server\n}\n```''',['Проверьте `caddy validate`.','Сравните curl к backend и через Caddy.','Оставьте cloud-init placeholder и объясните 503, затем замените конфигурацию.'],['TLS error до HTTP — проверять DNS/SNI/certificate.','502 — proxy не получил корректный ответ upstream; 503 может быть явной заглушкой.'],['deploy/yandex/Caddyfile','docs/deployment/DEPLOY_RUNBOOK.md']),
(8,'Git как история решений','После обновления библиотеки нужно понять, какая правка вызвала регрессию и как её отменить.',['Commit — снимок дерева плюс родители и сообщение; branch — перемещаемая ссылка. Git хранит историю объектов, а не последовательность «файловых патчей».','Index позволяет выбрать содержимое следующего commit. `git add -p` отделяет логические изменения.','Revert добавляет обратный commit и сохраняет общую историю; reset переписывает ссылку и опасен для опубликованной ветки.'],'''```bash\ngit switch -c docs/lesson\ngit diff\ngit add -p\ngit commit -m "docs: explain MAX session persistence"\ngit show --stat HEAD\n```''',['Сделайте два независимых commits.','Создайте конфликт в учебной ветке и разрешите осознанно.','Отмените один commit через revert.'],['CI красный после merge — сначала читать конкретный check.','Большой смешанный diff — разделить до review.'],['.github/workflows/quality.yml','CHANGELOG.md']),
(9,'YAML и .env как разные языки','Compose принял YAML, но service получил пустой пароль.',['YAML задаёт дерево данных: mapping, sequence и scalar. Валидный YAML может быть невалидным Compose, потому что schema — второй уровень проверки.','`.env` — пары KEY=VALUE, не YAML и не shell script. Compose interpolation выполняется до запуска container.','`${VAR:?message}` требует значение; `${VAR:-default}` разрешает fallback. Для security-параметров безопаснее обязательность, чем тихий default.'],'''```yaml\nservices:\n  backend:\n    env_file: ../../backend/.env\n    environment:\n      MONGO_URL: mongodb://mongo:27017\n    ports:\n      - "127.0.0.1:8001:8001"\n```''',['Проверьте `docker compose config`.','Сломайте indentation и затем schema key.','Добавьте обязательную переменную и убедитесь, что пустая конфигурация не запускается.'],['Parser error указывает синтаксис; unknown property — schema.','Значение выглядит числом/boolean — кавычки фиксируют строку.'],['deploy/yandex/docker-compose.yml','scripts/deployment/preflight.sh']),
(10,'Python-путь запроса: от socket до функции','Нужно понять, что именно происходит между POST `/api/leads` и записью в Mongo.',['Uvicorn принимает socket и вызывает ASGI application. FastAPI сопоставляет method/path с route, выполняет dependencies и validation.','`async def` позволяет уступать event loop во время I/O, но CPU-heavy код всё равно блокирует процесс.','Middleware оборачивает application. В `secure_server.py` body читается, проверяется consent и воспроизводится для FastAPI.'],'''```python\nif scope["method"] == "POST" and scope["path"] == "/api/leads":\n    body = b"".join(chunks)\n    payload = json.loads(body or b"{}")\n    if payload.get("consent") is not True:\n        return JSONResponse({"detail": "consent_required"}, status_code=400)\n```''',['Проследите один запрос по логам.','Напишите минимальный endpoint и Pydantic model.','Проверьте malformed JSON, отсутствие consent и корректный payload.'],['422 — schema validation, 400 здесь — policy middleware.','500 — необработанное исключение; искать traceback и request correlation.'],['backend/secure_server.py','backend/server.py','backend/tests/']),
(11,'MongoDB, persistence и consistency','После recreate backend заявки остаются, а после неправильного удаления volume исчезают.',['Mongo хранит BSON documents в collection. `_id` уникален; прикладной `id` требует собственного unique index, если по нему предотвращаются дубли.','Container writable layer связан с конкретным container. Named volume имеет отдельный lifecycle и монтируется в `/data/db`.','Dump — логическое представление базы; tar volume — файловое. Для работающей БД без coordination файловая копия может быть несогласованной.'],'''```bash\ndocker exec msp-mongo-1 mongosh mspshield --eval 'db.leads.countDocuments()'\nmongodump --uri mongodb://127.0.0.1:27017/mspshield --archive=lead.gz --gzip\nmongorestore --uri mongodb://127.0.0.1:27017/test --archive=lead.gz --gzip\n```''',['Создайте несколько documents.','Сделайте dump и restore в другую database.','Пересоздайте container с тем же volume и без него.'],['Повтор формы создаёт две записи — нет idempotency/unique constraint.','Dump есть, restore не проверен — recoverability неизвестна.'],['deploy/yandex/docker-compose.yml','migration/restic-backup.sh']),
(12,'Интеграции и durable outbox','Mongo сохранила заявку, но Kaiten был недоступен в момент отправки.',['Одновременную атомарность Mongo и внешнего HTTP API обычной транзакцией получить нельзя. Если сначала вызвать API — можно создать карточку без локальной записи; если сначала записать — можно потерять доставку.','Outbox сохраняет намерение доставки в той же надёжной системе, затем worker повторяет внешние вызовы. Это даёт at-least-once, поэтому потребитель или sender должны подавлять дубли.','Exponential backoff в проекте растёт от 30 секунд и ограничен 3600. Pending удаляется по каналам; завершённый job удаляется.'],'''```python\ndelay = min(3600, 30 * (2 ** min(attempts, 7)))\nawait db.crm_outbox.update_one(\n    {"lead_id": lead_id},\n    {"$set": {"attempts": attempts, "next_retry_at": now + timedelta(seconds=delay)}}\n)\n```''',['Подмените Kaiten fake-сервисом.','Верните 500 три раза, затем 201.','Докажите, что job переживает restart и карточка не дублируется.'],['Очередь растёт — смотреть oldest age, next_retry и last_errors.','Job удалён до подтверждения — риск потери доставки.'],['backend/secure_server.py','backend/integrations/']),
(13,'Frontend и форма как недоверенный клиент','Пользователь может вызвать API напрямую, минуя checkbox и JavaScript.',['SPA выполняется на машине пользователя: код и значения bundle доступны для чтения и изменения. Поэтому frontend validation улучшает UX, но не обеспечивает policy.','Build-time environment встраивается в assets; секрет, попавший туда, становится публичным.','Consent и CAPTCHA проверяются server-side. Fail-closed отклоняет запрос при недоступности verifier; fail-open — явное риск-решение.'],'''```bash\ncd frontend\nyarn install --frozen-lockfile\nyarn build\ngrep -R "ADMIN_TOKEN\\|PASSWORD" build/ || true\ncurl -i -X POST http://127.0.0.1:8001/api/leads -H 'Content-Type: application/json' -d '{}'
```''',['Соберите frontend.','Отправьте запрос без UI.','Проверьте отсутствие secrets и поведение consent/CAPTCHA.'],['Работает в dev, не в build — различие runtime/build config.','Checkbox есть, backend принимает false — UI не является control.'],['frontend/','backend/secure_server.py']),
(14,'Что Docker изолирует, а что нет','Container удалили и потеряли данные; ожидали, что image хранит runtime state.',['Image — неизменяемый набор слоёв; container — процесс с writable layer и namespaces. Удаление container удаляет его writable layer.','Volume живёт отдельно и предназначен для состояния. Bind mount показывает container конкретный host path и наследует его permissions.','Container не VM: ядро общее с host. Privileged/cAdvisor и docker.sock расширяют доверие и attack surface.'],'''```bash\ndocker run --name demo alpine sh -c 'echo x >/state && sleep 300'\ndocker rm -f demo\ndocker volume create demo-data\ndocker run --rm -v demo-data:/data alpine sh -c 'echo y >/data/state'\ndocker run --rm -v demo-data:/data alpine cat /data/state\n```''',['Сравните writable layer и volume.','Исследуйте PID и network namespace.','Объясните host binding `127.0.0.1:8001:8001`.'],['Данные пропали — состояние было не в volume.','Порт недоступен извне — это может быть намеренный loopback binding.'],['deploy/yandex/docker-compose.yml']),
(15,'Dockerfile, cache и attack surface','Нужно собрать backend воспроизводимо и не запускать его как root без причины.',['`FROM` задаёт базовый filesystem. `COPY` и `RUN` создают layers; изменение раннего layer инвалидирует последующий cache.','Build context определяет, какие файлы доступны `COPY`; секреты не должны попадать в context или layer history.','`CMD` задаёт default process. Production image проекта запускает `secure_server:app`, чтобы consent/CAPTCHA/outbox policy нельзя было обойти.'],'''```dockerfile\nFROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["uvicorn", "secure_server:app", "--host", "0.0.0.0", "--port", "8001"]\n```''',['Соберите image дважды и сравните cache.','Добавьте non-root user.','Проверьте image history на secrets.'],['Сборка всегда долгая — часто requirements копируются после всего source.','Container стартует, policy нет — указан `server:app` вместо wrapper.'],['deploy/yandex/Dockerfile.backend','backend/secure_server.py']),
(16,'Compose как граф зависимостей','Backend должен ждать Mongo, но restart policy не исправляет логическую ошибку приложения.',['Compose project объединяет services, networks и volumes. Service — шаблон container, а не сам process.','`depends_on: condition: service_healthy` регулирует порядок старта, но не лечит будущий отказ зависимости. Приложению нужны timeout/retry.','Два Compose-проекта связываются через external network `msp_default`; имя должно уже существовать.'],'''```yaml\nbackend:\n  depends_on:\n    mongo:\n      condition: service_healthy\n  ports:\n    - "127.0.0.1:8001:8001"\n```''',['Поднимите Mongo+backend.','Сделайте Mongo unhealthy после старта.','Сравните `restart` и `up -d --force-recreate` после изменения env.'],['Compose config ok, external network missing — runtime prerequisite.','`restart` не перечитал env — нужен recreate.'],['deploy/yandex/docker-compose.yml','deploy/yandex/monitoring/docker-compose.yml']),
(17,'Облако и VM с нуля','Чистая VM должна стать предсказуемой базой, а не ручной уникальной машиной.',['VM объединяет compute, disk и network interface; public IP обычно реализуется NAT. Security group фильтрует на уровне облака, ufw — на host.','cloud-init выполняет bootstrap один раз. Маркер готовности должен появляться только после фактической проверки Docker/Caddy/Node/unzip.','Service account и ключи ограничиваются необходимыми ролями. Удаление VM не всегда удаляет static IP, snapshots и buckets.'],'''```bash\nyc compute instance create --name msp-lab \\\n  --zone ru-central1-a --memory 4 --cores 2 \\\n  --network-interface subnet-name=default,nat-ip-version=ipv4 \\\n  --metadata-from-file user-data=deploy/yandex/cloud-init.yaml\n```''',['Создайте lab VM.','Проверьте cloud-init log и инструменты.','Составьте resource inventory и удалите всё после lab.'],['apt завис на IPv6 — использовать диагностированный ForceIPv4, а не бесконечный retry.','IP сменился после stop/start — нужен reserved static IP.'],['deploy/yandex/cloud-init.yaml','docs/deployment/DEPLOY_RUNBOOK.md']),
(18,'Полный deploy MSPShield','Нужно развернуть систему на чистой VM и понимать каждый gate.',['Порядок уменьшает число неизвестных: base VM → code → env → preflight → application → monitoring → Caddy → DNS → external checks.','Preflight проверяет наличие env, BOM/CRLF, обязательные ключи, Compose render, secure entrypoint и небезопасный SSH bypass; `--fix` имеет ограниченные side effects и backup.','DNS переключается последним, после проверки нового IP из целевого региона. Иначе исправная VM может быть недоступна клиентам.'],'''```bash\ncd /opt/msp/Newbie\nsudo bash scripts/deployment/preflight.sh --fix\ncd deploy/yandex && docker compose up -d\ncd monitoring && docker compose up -d\ncurl -fsS http://127.0.0.1:8001/api/health\n```''',['Выполните deploy на пустой VM.','После каждого шага снимите state evidence.','Проведите внешний TCP/TLS/HTTP smoke test до DNS switch.'],['503 — проверить provisioning placeholder и MSP_DOMAIN.','Пустой webroot — frontend build/setup не выполнен.'],['docs/deployment/DEPLOY_RUNBOOK.md','scripts/deployment/preflight.sh']),
(19,'SMTP, DNS и Stalwart/Postbox','Письма принимаются локально, но наружу копятся с 535.',['SMTP envelope MAIL FROM/RCPT TO управляет доставкой и отличается от видимых From/To headers. Relay требует authentication и policy.','MX указывает принимающий host; SPF разрешает senders; DKIM подписывает письмо; DMARC задаёт policy и alignment. В Postbox DKIM публикуется CNAME из консоли.','Stalwart хранит route credentials в собственной БД. Восстановление старой БД может вернуть старый ключ, даже если `.env` обновлён. Очередь JMAP показывает реальную 535.'],'''```bash\ncurl -s -u "admin:$PW" -H 'Content-Type: application/json' \\\n -d '{"using":["urn:ietf:params:jmap:core","urn:stalwart:jmap"],"methodCalls":[["x:QueuedMessage/get",{},"0"]]}' \\\n http://127.0.0.1:8080/jmap/\n```''',['Проверьте DNS records.','Получите очередь JMAP.','Обновите route на тестовом стенде и restart Stalwart.'],['535 — credential/identity, не сетевой timeout.','Bootstrap mode — не восстановлен `stalwart-data` или `stalwart-etc`.'],['docs/deployment/MIGRATION_RUNBOOK.md','deploy/yandex/docker-compose.yml']),
(20,'Метрики и Prometheus','Dashboard красивый, но Owner не понимает, что измеряет график.',['Metric sample состоит из имени, labels, timestamp и value. Counter только растёт до restart; gauge может расти и падать; histogram распределяет observations по buckets.','Prometheus сам scrape targets. `up=1` означает успешный scrape, а не исправность бизнес-функции.','Каждая комбинация labels создаёт series. User ID или URL с уникальным query ведёт к cardinality explosion.'],'''```promql\nup{job="backend"}\nrate(http_requests_total{status=~"5.."}[5m])\nhistogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))\n```''',['Найдите targets и scrape errors.','Постройте три запроса.','Объясните каждую функцию и label matcher.'],['No data — target/selector/retention, а не нулевое значение.','Высокий CPU Prometheus — проверить cardinality и query.'],['deploy/yandex/monitoring/docker-compose.yml','deploy/yandex/monitoring/prometheus/']),
(21,'Alerting и доставка в MAX','Alert firing виден в Prometheus, но сообщение не приходит в MAX.',['Rule переводит metric expression в alert state. `for` требует непрерывного выполнения условия и подавляет краткий шум.','Alertmanager группирует и маршрутизирует alerts; webhook получает JSON и bearer token.','MAX alerter использует pymax user session, не официальный bot API. `max.db` — credential; version 2.4.1 закреплена после unsupported-version. Health endpoint не доказывает отправку.'],'''```bash\nsudo docker exec msp-max-alerter python -m max_alerter.auth\ncurl -fsS http://127.0.0.1:9095/health\nsudo docker logs msp-max-alerter --tail 100\n```''',['Авторизуйте test account: SMS, затем 2FA.','Отправьте тестовый webhook из monitoring network.','Перезагрузите container/VM и подтвердите session persistence.'],['401 — webhook tokens различаются.','Health ok, send fail — session/chat ID/library/API.'],['docs/MAX_SETUP.md','services/max_alerter/README.md','deploy/yandex/monitoring/docker-compose.yml']),
(22,'Backup, restore, RPO и RTO','Backup job зелёный, но никто не знает, можно ли восстановить сервис.',['Backup — копия определённого набора данных; snapshot — зафиксированное состояние repository. Ни одно слово не означает автоматически consistency.','RPO измеряет допустимую потерю по времени, RTO — время восстановления сервиса. Цель становится доказанной только в упражнении.','MSPShield требует Mongo dump, Vaultwarden data, оба Stalwart volumes и MAX session. Ключи repository и restore credentials — отдельная зависимость.'],'''```bash\nsudo bash /opt/restic-scripts/backup.sh\nsource /etc/restic/env.sh\nrestic snapshots --latest 1\nrestic check\nrestic restore latest --target /tmp/restore-test\n```''',['Сделайте snapshot.','Восстановите в clean target, не поверх production.','Поднимите сервис и измерьте RPO/RTO.'],['Snapshot есть, размер 0 — capture path неверен.','Repository доступен, password потерян — restore невозможен.'],['migration/restic-backup.sh','docs/deployment/disaster_recovery.md']),
(23,'Миграция и Disaster Recovery','Нужно перенести проект в новый аккаунт без потери данных и с возможностью отката.',['Migration — плановое перемещение; DR — восстановление после серьёзного отказа. Шаги похожи, но доступность исходной системы и допустимый риск различаются.','Cutover меняет направление production traffic. До него новая среда проверяется по IP/hosts override; после — действует observation window.','Restore script обязан fail closed при пустом томе. Для Stalwart восстанавливаются etc и data; иначе bootstrap выглядит как «сервис запущен», но конфигурации нет.'],'''```bash\nsudo bash -c 'source /etc/restic/env.sh && restic restore latest --target /tmp/restore'\nsudo MIGRATION_DIR=/tmp/migration bash migration/restore-on-vm.sh\ndocker logs msp-stalwart-1 | grep -c 'bootstrap mode'\n```''',['Составьте inventory до переноса.','Перенесите на clean VM и проверьте data counts/volume sizes.','Отрепетируйте DNS cutover и rollback.'],['ICMP ok, TCP timeout — сменить IP до DNS.','Новый bucket даёт SignatureDoesNotMatch — credentials связаны с аккаунтом.'],['docs/deployment/MIGRATION_RUNBOOK.md','migration/restore-on-vm.sh']),
(24,'Secrets, Vaultwarden и доступ','Новый администратор должен получить минимальный доступ и потерять его при offboarding.',['Secret даёт возможность действовать от имени identity. Его lifecycle: создать, передать, использовать, ротировать, отозвать, уничтожить.','Vaultwarden хранит значения и sharing; Kaiten хранит задачу и факт выдачи, но не пароль. Git содержит `.env.example`, а не `.env`.','MFA снижает риск украденного пароля, но recovery codes сами являются secrets. Break-glass доступ должен быть ограничен и проверяем.'],'''```bash\numask 077\nopenssl rand -hex 32 > /tmp/token\nchmod 600 deploy/yandex/monitoring/.env\ngit status --ignored --short\n```''',['Создайте collection для test client.','Выдайте Junior один credential и проверьте границу.','Отзовите доступ и ротируйте secret.'],['Секрет в ticket — удалить/ротировать, не просто скрыть сообщение.','Compose config показал secret — не прикладывать полный вывод.'],['docs/deployment/secrets_management.md','docs/deployment/VAULTWARDEN_ORG_RUNBOOK.md']),
(25,'Харденинг и безопасные изменения','Нужно закрыть публичный SSH, не потеряв управление VM.',['Defense in depth: cloud SG и ufw независимы. Закрытие только одного слоя оставляет зависимость от другого.','Сначала проверяется AWG tunnel, routing и SSH к private VPN address. Затем удаляется public rule.','Break-glass заранее описывает возврат временного public rule, repair и повторное закрытие. Это не постоянный bypass.'],'''```bash\nsudo ufw delete allow 22/tcp\nsudo ufw status numbered\nnc -vz PUBLIC_IP 22\nssh ubuntu@10.9.0.1\n```''',['Поднимите test tunnel.','Закройте 22 на host и SG.','С другого канала выполните break-glass и снова закройте.'],['Закрыли до проверки VPN — использовать cloud console/temporary SG по runbook.','VPN работает, DNS нет — SSH по private IP отделяет проблемы.'],['docs/deployment/DEPLOY_RUNBOOK.md','migration/README.md']),
(26,'Incident, problem, change и service review','Нужно восстановить сайт и не превратить расследование в хаотичные команды.',['Incident управляет текущим impact; problem ищет повторяемую причину; change изменяет controlled state. Один ticket может породить все три записи.','Mitigation уменьшает impact, root cause объясняет механизм. Перезапуск может быть mitigation, но не доказательством причины.','Timeline строится по timestamped evidence. Postmortem отделяет contributing conditions от персонального обвинения.'],'''```text\n14:02 alert: external probe failed\n14:05 owner acknowledged P1\n14:09 direct backend health=200, Caddy=503\n14:14 replaced provisioning Caddyfile\n14:17 external HTTPS=200\n```''',['Проведите tabletop Caddy 503.','Назначьте incident lead и communications.','Сформулируйте preventive action с owner/date/test.'],['Много людей меняют систему — остановить некоординированные changes.','Нет исходного состояния — фиксировать текущие факты, не реконструировать уверенно.'],['docs/runbooks/README.md','docs/post_mortem_template.md']),
(27,'Технический capstone: построить аналог с нуля','Теперь нельзя копировать готовый Compose целиком: нужно доказать перенос модели.',['Минимальный аналог: public TLS proxy, API, persistent DB, metrics, alert webhook и encrypted backup. Компоненты можно заменить, если объяснены interfaces и recovery.','Architecture decision сравнивает варианты по требованиям, failure domains, операционной цене и обратимости. «Популярнее» не является достаточным критерием.','Definition of done включает clean restore и handover другому человеку.'],'''```text\nПустая VM → hardening baseline → app/data → TLS → metrics/alerts\n→ backup → destructive test → clean restore → handover\n```''',['Напишите design до deploy.','Разверните без копирования project compose.','Передайте runbook другому человеку и исправьте непонятные места.'],['Работает только у автора — нет воспроизводимости.','Есть backup, нет restore — capstone не принят.'],['docs/deployment/DEPLOY_RUNBOOK.md','docs/training/DEPLOYMENT_MIGRATION_LABS.md']),
(28,'Деньги и время: язык модели','Цена 25 000 ₽ кажется выручкой, но Owner должен знать, сколько остаётся после труда и риска.',['Revenue признаёт продажу; cash flow показывает движение денег. При авансе cash может прийти раньше оказания услуги.','Contribution = revenue − переменные прямые затраты − оценённый труд − transaction costs − incident reserve. Он ещё не равен чистой прибыли: fixed costs остаются.','Стоимость труда не равна выводу денег со счёта. Даже бесплатное время Owner ограничивает capacity и должно оцениваться.'],'''```text\nBronze: 25 000 − 5 000 инженер − 1 500 SM − 1 750 налог/банк − 600 резерв\n= 16 150 ₽ contribution; margin = 16 150 / 25 000 = 64,6%\n```''',['Соберите модель Bronze.','Измените часы труда ±20%.','Разделите P&L и cash timing.'],['Высокая margin, нет денег — проверить дебиторку/аванс/cash.','Труд Owner = 0 — модель скрывает ограничение.'],['commercial/PRICING.md','technical/BUSINESS_MODEL.md']),
(29,'Capacity и путь от подработки к команде','Два человека обслуживают клиентов вечером и должны понимать момент перегрузки.',['Capacity начинается с календарного времени, затем вычитаются отдых, продажи, admin, обучение и reserve. Utilization 100% оставляет ноль для incidents и приводит к срыву SLA.','WIP ограничивает число одновременно незавершённых задач. Context switching увеличивает время и число ошибок.','Gold требует независимых responders и service manager. Наличие контакта подрядчика не равно готовой ротации.'],'''```text\nДоступно 80 ч/мес × 0,65 productive = 52 ч\n− 12 ч sales/admin − 10 ч reserve = 30 ч плановой клиентской работы\n```''',['Посчитайте capacity на 2/5/10 клиентов.','Добавьте один P1 и отпуск.','Определите trigger найма и waitlist.'],['Revenue растёт, SLA падает — capacity gate отсутствует.','Bus factor=1 — документация не заменяет второго допущенного responder.'],['docs/operations/PILOT_OPERATING_MODEL.md','technical/SCALING.md']),
(30,'Из технического scope в пакет и цену','Клиент просит «всё администрирование», но такой scope нельзя оценить и принять.',['Периметр превращает абстрактную поддержку в перечень объектов, критичности, разрешённых действий и зависимостей.','Цена строится снизу: труд + переменные расходы + reserve + целевая contribution. Пакет упрощает продажу, но Order Form уточняет реальный scope.','Discount уменьшает contribution на полный размер скидки. Скидка оправдана только встречным улучшением: prepayment, срок, меньший scope.'],'''```text\nМинимальная цена при cost=18 250 и margin floor=50%:\nprice = cost / (1 − 0,50) = 36 500 ₽\n```''',['Соберите perimeter учебного клиента.','Оцените часы и reserve.','Сравните Bronze/Silver/custom и проверьте скидку.'],['Пакет выбран только по числу VM — игнорируются criticality/dependencies.','Gold 120k ниже floor после ротации — повысить цену или изменить scope.'],['commercial/PRICING.md','technical/1_Bronze/Bronze.md','technical/2_Silver/Silver.md','technical/3_Gold/Gold.md']),
(31,'ICP и ценностное предложение без тумана','Нужно понять, кому услуга действительно подходит, до затрат на аудит.',['Segment — группа с общим признаком; ICP добавляет наблюдаемые условия хорошей экономики и результата. Persona описывает роль в покупке, а не выдуманный характер человека.','Pain — текущая проблема; impact — последствие в деньгах, риске или времени; trigger — событие, повышающее срочность.','Value proposition связывает конкретного клиента, проблему, результат и доказательство. Список технологий не является ценностью.'],'''```text\nДля российских B2B-команд с 3–15 VM, где нет выделенного ops,\nмы создаём наблюдаемый backup/monitoring baseline и управляем incidents\nв согласованном окне; доказательство — restore report и monthly review.\n```''',['Разберите 10 компаний по наблюдаемым признакам.','Сформулируйте anti-ICP.','Проведите пять problem interviews без pitch.'],['Каждому «нужен мониторинг» — утверждение не проверено.','ICP слишком широкий — qualification не отсекает нагрузку.'],['commercial/ADS.md','commercial/SALES_PLAYBOOK.md']),
(32,'Воронка как управляемый процесс','Карточки находятся в Proposal месяцами, но реального следующего действия нет.',['Stage — состояние сделки с entry/exit criteria. Действие продавца не является выходом, если клиент не совершил требуемый commitment.','Conversion использует одну когорту или корректно определённый период. Median stage age устойчивее среднего при редких долгих сделках.','Sales velocity объединяет число возможностей, win rate, средний чек и cycle; рост одного множителя может ухудшить margin/capacity.'],'''```text\nNew → Qualified → Discovery → Proposal\n→ Gold Capacity Check (если нужен) → Contract → Won/Lost/Waitlist\n```''',['Настройте поля и exit criteria в Kaiten.','Проведите три учебные сделки.','Посчитайте conversion и age вручную.'],['Карточка без next action — фактически stalled.','Proposal до authority/need — создаёт бумажную активность.'],['commercial/SALES_FUNNEL.md','docs/KAITEN_SETUP.md']),
(33,'Discovery и безопасный pre-audit','Нужно понять систему клиента, не начиная несанкционированное сканирование.',['Discovery собирает current state, desired state, impact, authority, timing, budget и constraints. Ответ отмечается как факт клиента, наблюдение или предположение.','Active scan меняет профиль риска и требует письменного разрешения с target, временем и ограничениями. Публичный IP не означает разрешение.','Хороший discovery заканчивается решением: no-fit, дополнительная диагностика или предложение с известными unknowns.'],'''```text\nФакт: 8 VM, ответ клиента, inventory не проверен.\nНаблюдение: внешний HTTPS доступен, письменное разрешение №...\nUnknown: проверяемость backup; до restore drill RTO не подтверждён.\n```''',['Проведите интервью по mock-сценарию.','Составьте perimeter и unknowns.','Напишите authorization scope для одного безопасного scan.'],['Клиент говорит «backup есть» — это claim, не restore evidence.','Бюджет неизвестен — не придумывать, назначить следующий вопрос.'],['commercial/SALES_PLAYBOOK.md','scripts/pre_audit.py']),
(34,'КП, переговоры и скидки','Клиент говорит «дорого» и просит 20% без изменения объёма.',['Proposal связывает подтверждённую проблему, scope, exclusions, результат, onboarding, recurring price и next step.','Возражение уточняется: нет ценности, нет бюджета, не тот timing, риск доверия или сравнение с альтернативой.','Concession обменивается на встречное условие. Бесплатное расширение scope разрушает и margin, и capacity.'],'''```text\nSilver 50 000; cost 18 250.\nСкидка 5% → revenue 47 500; contribution 29 250; margin 61,6%.\nСкидка 20% → revenue 40 000; contribution 21 750; margin 54,4%,\nно запас на ошибку и рост часов значительно ниже.\n```''',['Сделайте два options.','Разыграйте «дорого», «дайте 24/7», «сначала бесплатно почините».','Пересчитайте каждую уступку.'],['Скидка без срока — становится постоянной ценой.','24/7 в тексте до capacity approval — недопустимое обещание.'],['commercial/PROPOSAL.md','commercial/PRICING.md']),
(35,'Договор, SLA, Периметр и ПДн','Коммерческое обещание должно совпасть с технической способностью и capacity.',['MSA задаёт общие правила; Order Form — цену и пакет; Периметр — конкретные объекты; DPA — поручение по ПДн. Приоритет документов устраняет конфликт.','Reaction time — начало работы, не восстановление. RTO зависит от системы и подтверждается test. Monitoring 24/7 не создаёт человеческую реакцию 24/7.','Liability, service credit и exclusions распределяют риск, но шаблон требует юридической проверки РФ.'],'''```text\nP1 Gold: реакция до 1 часа только в подписанное окно.\n24/7 возникает после capacity approval, ротации, drills и Order Form.\n```''',['Заполните договор mock-клиента.','Сопоставьте каждое SLA с monitoring/alert/staffing.','Отметьте legal-open-items.'],['Периметр пуст — услуга фактически безгранична.','RTO указан без restore test — оставить как target.'],['contracts/MSP_SERVICE_AGREEMENT.md','contracts/README.md']),
(36,'Onboarding, steady state и offboarding','Подписанный клиент ещё не должен автоматически попадать под SLA.',['Pre-onboarding проверяет оплату, документы, contacts и доступность inputs. Technical onboarding создаёт inventory, access, baseline, monitoring и backup.','Acceptance переводит систему в steady state только после оговорённых checks. Unknown technical debt фиксируется, а не молча принимается.','Offboarding возвращает данные, отзывает accounts и фиксирует deletion/retention. Owner клиента сохраняет recovery control.'],'''```text\nWon → pre-onboarding gate → technical onboarding\n→ acceptance → operation/review → renewal или offboarding\n```''',['Проведите mock-client через lifecycle.','Создайте access matrix и baseline.','Выполните offboarding и найдите orphan access.'],['SLA начался до acceptance — риск ложного breach.','Секреты в Kaiten — перенести в Vaultwarden и ротировать.'],['docs/operations/CLIENT_LIFECYCLE.md','docs/onboarding/README.md']),
(37,'Owner dashboard и управленческие решения','Метрик много, но ни одна не меняет решение.',['MRR — нормализованная recurring revenue; contribution MRR лучше показывает ресурс на fixed costs. ARR = MRR×12 только при стабильной модели.','Logo churn считает клиентов, MRR churn — потерянную выручку. NRR учитывает expansion и contraction; cohort не смешивает клиентов разного возраста.','CAC включает согласованный набор acquisition costs. Payback = CAC / monthly contribution, а не revenue. LTV молодого бизнеса — гипотеза с sensitivity.'],'''```text\nSales velocity = opportunities × win_rate × average_deal / sales_cycle_days\nCAC payback = CAC / monthly contribution\nNRR = (start MRR − churn − contraction + expansion) / start MRR\n```''',['Постройте 12 месяцев synthetic data.','Рассчитайте метрики вручную и формулами.','Для каждого порога назначьте решение.'],['Высокий MRR при низкой contribution — рост может ухудшать cash.','Средний CAC без определения расходов — несравним.'],['technical/BUSINESS_MODEL.md','commercial/SALES_FUNNEL.md']),
(38,'Финальный бизнес-capstone','Нужно принять или отклонить реального по структуре клиента и защитить решение.',['Capstone объединяет technical feasibility, capacity, unit economics, sales ethics и contract boundaries.','Хорошее решение может быть `waitlist` или `no`. Продажа, разрушающая SLA существующих клиентов, не является успехом.','Каждая цифра имеет источник и sensitivity; каждое обещание — owner, процесс и evidence.'],'''```text\nICP → discovery → perimeter → architecture → effort/capacity\n→ price/margin → proposal → contract → onboarding 90 days\n→ owner dashboard\n```''',['Получите mock case с неполными данными.','Задайте вопросы, не дополняя факты.','Подготовьте decision pack и защитите accept/waitlist/no-fit.'],['Gold без responders/drills/legal review — только capacity check.','Margin проходит только при нулевой цене Owner time — модель отклонить.'],['commercial/README.md','contracts/MSP_SERVICE_AGREEMENT.md','docs/operations/CLIENT_LIFECYCLE.md']),
]

def chapter(d):
 n,title,scenario,concepts,example,steps,failures,paths=d
 prev=f'Предыдущая глава: [глава {n-1}](./{n-1:02d}-'+slug(D[n-2][1])+'.md).' if n>1 else 'Начните с общей карты и не переходите к production-командам.'
 lines=[f'# {n}. {title}','',f'> **Учебная ситуация.** {scenario}','',prev,'',
 '## Модель, которую нужно построить','']
 for p in concepts: lines += [p,'']
 lines += ['## Разобранный пример','',example,'', 'Разбирайте пример слева направо. Сначала определите программу или формат, затем входные данные, изменяемое состояние и способ наблюдения. Не переносите команду в production, пока не можете предсказать её side effects.','']
 # Specific code line explanations
 code='\n'.join(x for x in example.splitlines() if not x.startswith('```'))
 if code:
  lines += ['### Как читать пример','']
  for ln in code.splitlines()[:8]:
   if ln.strip(): lines += [f'- `{ln.strip()}` — найдите в документации владельца синтаксиса и объясните, что эта строка читает или изменяет.']
 lines += ['','## Практикум','']
 for i,s in enumerate(steps,1): lines += [f'{i}. {s}']
 lines += ['','Практикум выполняется на lab VM, тестовой ветке или synthetic dataset. Перед командой с удалением, изменением firewall, DNS, volume, restore `--drop` или production credentials запишите rollback и получите согласование.','',
 '## Если результат не совпал с ожиданием','', '| Наблюдение | Что это означает | Следующая проверка |','|---|---|---|']
 for f in failures:
  if ' — ' in f:
   a,b=f.split(' — ',1)
  else:
   a,b=f,'Проверьте связанные входы, состояние и журналы; не угадывайте причину.'
  lines += [f'| {a} | Это сужает область поиска, но не доказывает единственную причину | {b} |']
 lines += ['','## Самостоятельная работа','',f'Воспроизведите ситуацию главы «{title}» на другом объекте или с другим входом. Не копируйте разобранный пример целиком. Сдайте схему, команды, сокращённый вывод без секретов, объяснение результата и один намеренно вызванный отказ с восстановлением.','',
 '## Проверка понимания','',
 '1. Что в этой главе является состоянием и где оно хранится?','2. Как отличить успешное выполнение команды от достижения результата?','3. Какой похожий симптом имеет другую причину?','4. Как безопасно отменить изменение?','5. Как техническое решение влияет на время, риск или деньги?','',
 '## Источники проекта','']
 for p in paths: lines += [f'- [{p}]({repo+p})']
 lines += ['', '- [Кураторская видеотека и порядок практики](../VIDEO_GUIDE.md)', '',
 '## Условие перехода','',f'Переходите дальше, когда можете без текста объяснить механизм главы {n}, выполнить практикум и восстановиться после ошибки. Если вы только узнаёте команды, но не предсказываете результат, повторите lab.','']
 return '\n'.join(lines)

def slug(s):
 s=s.lower().replace('ё','е'); s=re.sub(r'[^a-zа-я0-9]+','-',s).strip('-'); return s
manifest=[]
for d in D:
 n,title,*_=d; fn=f'{n:02d}-{slug(title)}.md'; (C/fn).write_text(chapter(d),encoding='utf-8'); manifest.append((n,title,fn))
# book navigation
parts=[(1,'Научиться видеть систему',1,2),(2,'Linux и сеть',3,7),(3,'Код и конфигурация',8,13),(4,'Контейнеры и deploy',14,18),(5,'Production и эксплуатация',19,27),(6,'Экономика MSP',28,30),(7,'Продажи и lifecycle',31,38)]
b=['# MSPShield Academy','',f'Версия проекта: `{commit}`. Формат: отдельные Markdown-главы.','',
'Учебник рассчитан на Junior-сисадмина. Идите последовательно: знания вводятся до первого использования. Практикумы выполняйте на отдельной VM. Критерий завершения — самостоятельное действие и восстановление после ошибки, а не чтение текста.','',
'## Как учиться','','1. Прочитайте ситуацию и сначала запишите собственную гипотезу.','2. Разберите пример построчно; неизвестный токен найдите в официальной документации.','3. Выполните guided lab.','4. Закройте текст и выполните самостоятельную работу.','5. Через неделю повторите ключевую команду и объяснение из памяти.','6. Ведите `learning-log.md`: дата, задача, ошибка, механизм, исправление.','']
for _,name,a,z in parts:
 b += [f'## {name}','']
 for n,title,fn in manifest[a-1:z]: b += [f'{n}. [{title}](chapters/{fn})']
 b += ['']
b += ['## Приложения','','- [Стандарт написания и контроль фактов](00_AUTHORING_STANDARD.md)','- [Исходная карта программы](00_BOOK_MAP.md)','- [Глоссарий](GLOSSARY.md)','- [Ответы и подсказки преподавателю](INSTRUCTOR_NOTES.md)','']
(R/'BOOK.md').write_text('\n'.join(b),encoding='utf-8')
# glossary concrete
terms={'ASGI':'Протокол взаимодействия Python web-server и asynchronous application. Uvicorn принимает сеть и вызывает FastAPI через ASGI.','Bind mount':'Отображение конкретного host path внутрь container; lifecycle и permissions принадлежат host.','Capacity':'Количество работы, которое команда может выполнить за период после вычета обязательных непроектных затрат и резерва.','Contribution':'Выручка минус прямые переменные расходы, оценённый труд, transaction costs и резерв конкретной услуги.','Container':'Процесс с настроенными Linux namespaces/cgroups и filesystem из image плюс writable layer; не отдельная VM.','Idempotency':'Свойство операции, при котором повтор с тем же ключом не создаёт второй бизнес-результат.','RPO':'Максимально допустимый возраст потерянных данных; фактическое значение определяется интервалом и успешностью restore.','RTO':'Время от начала восстановления до принятого работоспособного состояния; подтверждается упражнением.','SLA reaction':'Время до подтверждения и начала диагностики в согласованном окне; не время полного восстановления.','Source of truth':'Согласованное место, которому доверяют конкретный тип факта: договор, Git, vault, ticket system или telemetry.','Volume':'Docker-managed storage с lifecycle отдельно от container.','Working example':'Полностью разобранный образец решения с пояснением причин каждого шага.'}
g=['# Глоссарий','']
for k,v in sorted(terms.items()): g += [f'## {k}','',v,'']
(R/'GLOSSARY.md').write_text('\n'.join(g),encoding='utf-8')
# instructor notes with answers principles
(R/'INSTRUCTOR_NOTES.md').write_text('''# Заметки преподавателю\n\nНе принимайте пересказ команды. Просите ученика предсказать результат, назвать изменяемое состояние и показать независимую проверку.\n\n## Оценивание\n\n- 0 — узнаёт термин, выполнить не может.\n- 1 — выполняет по инструкции, не диагностирует отклонение.\n- 2 — выполняет без подсказки и исправляет типовой отказ.\n- 3 — переносит модель на другой инструмент, объясняет trade-offs и обучает другого.\n\nДля production допуска требуется уровень 2 по главам 3–26 и успешные capstone 27/38. Юридические решения, критичная security-архитектура и 24/7 Gold требуют внешнего профильного review независимо от учебной оценки.\n''',encoding='utf-8')
(R/'manifest.json').write_text(json.dumps([{'n':n,'title':t,'file':f} for n,t,f in manifest],ensure_ascii=False,indent=2),encoding='utf-8')
print('BUILT',len(D))
